/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedSecretaryIndexRouteImport } from './routes/_authenticated/secretary/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSecretaryScannerRouteImport } from './routes/_authenticated/secretary/scanner'
import { Route as AuthenticatedSecretaryReceptionRouteImport } from './routes/_authenticated/secretary/reception'
import { Route as AuthenticatedSecretaryPaymentsRouteImport } from './routes/_authenticated/secretary/payments'
import { Route as AuthenticatedSecretaryGroupsRouteImport } from './routes/_authenticated/secretary/groups'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin/teachers'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminSecretariesRouteImport } from './routes/_authenticated/admin/secretaries'
import { Route as AuthenticatedAdminScannerRouteImport } from './routes/_authenticated/admin/scanner'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated/admin/groups'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminAcademicYearsRouteImport } from './routes/_authenticated/admin/academic-years'
import { Route as AuthenticatedSecretaryStudentsNewRouteImport } from './routes/_authenticated/secretary/students/new'
import { Route as AuthenticatedSecretaryStudentsIdRouteImport } from './routes/_authenticated/secretary/students/$id'
import { Route as AuthenticatedAdminStudentsNewRouteImport } from './routes/_authenticated/admin/students/new'
import { Route as AuthenticatedAdminStudentsIdRouteImport } from './routes/_authenticated/admin/students/$id'
import { Route as AuthenticatedAdminPaymentsSettingsRouteImport } from './routes/_authenticated/admin/payments.settings'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecretaryIndexRoute =
  AuthenticatedSecretaryIndexRouteImport.update({
    id: '/secretary/',
    path: '/secretary/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecretaryScannerRoute =
  AuthenticatedSecretaryScannerRouteImport.update({
    id: '/secretary/scanner',
    path: '/secretary/scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecretaryReceptionRoute =
  AuthenticatedSecretaryReceptionRouteImport.update({
    id: '/secretary/reception',
    path: '/secretary/reception',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecretaryPaymentsRoute =
  AuthenticatedSecretaryPaymentsRouteImport.update({
    id: '/secretary/payments',
    path: '/secretary/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecretaryGroupsRoute =
  AuthenticatedSecretaryGroupsRouteImport.update({
    id: '/secretary/groups',
    path: '/secretary/groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/admin/teachers',
    path: '/admin/teachers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSecretariesRoute =
  AuthenticatedAdminSecretariesRouteImport.update({
    id: '/admin/secretaries',
    path: '/admin/secretaries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminScannerRoute =
  AuthenticatedAdminScannerRouteImport.update({
    id: '/admin/scanner',
    path: '/admin/scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/admin/groups',
    path: '/admin/groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/admin/attendance',
    path: '/admin/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAcademicYearsRoute =
  AuthenticatedAdminAcademicYearsRouteImport.update({
    id: '/admin/academic-years',
    path: '/admin/academic-years',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecretaryStudentsNewRoute =
  AuthenticatedSecretaryStudentsNewRouteImport.update({
    id: '/secretary/students/new',
    path: '/secretary/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecretaryStudentsIdRoute =
  AuthenticatedSecretaryStudentsIdRouteImport.update({
    id: '/secretary/students/$id',
    path: '/secretary/students/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudentsNewRoute =
  AuthenticatedAdminStudentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)
const AuthenticatedAdminStudentsIdRoute =
  AuthenticatedAdminStudentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)
const AuthenticatedAdminPaymentsSettingsRoute =
  AuthenticatedAdminPaymentsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminPaymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/academic-years': typeof AuthenticatedAdminAcademicYearsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRouteWithChildren
  '/admin/scanner': typeof AuthenticatedAdminScannerRoute
  '/admin/secretaries': typeof AuthenticatedAdminSecretariesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/secretary/groups': typeof AuthenticatedSecretaryGroupsRoute
  '/secretary/payments': typeof AuthenticatedSecretaryPaymentsRoute
  '/secretary/reception': typeof AuthenticatedSecretaryReceptionRoute
  '/secretary/scanner': typeof AuthenticatedSecretaryScannerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/secretary/': typeof AuthenticatedSecretaryIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/admin/payments/settings': typeof AuthenticatedAdminPaymentsSettingsRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/secretary/students/$id': typeof AuthenticatedSecretaryStudentsIdRoute
  '/secretary/students/new': typeof AuthenticatedSecretaryStudentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/academic-years': typeof AuthenticatedAdminAcademicYearsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRouteWithChildren
  '/admin/scanner': typeof AuthenticatedAdminScannerRoute
  '/admin/secretaries': typeof AuthenticatedAdminSecretariesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/secretary/groups': typeof AuthenticatedSecretaryGroupsRoute
  '/secretary/payments': typeof AuthenticatedSecretaryPaymentsRoute
  '/secretary/reception': typeof AuthenticatedSecretaryReceptionRoute
  '/secretary/scanner': typeof AuthenticatedSecretaryScannerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/secretary': typeof AuthenticatedSecretaryIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/admin/payments/settings': typeof AuthenticatedAdminPaymentsSettingsRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/secretary/students/$id': typeof AuthenticatedSecretaryStudentsIdRoute
  '/secretary/students/new': typeof AuthenticatedSecretaryStudentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/student/login': typeof StudentLoginRoute
  '/_authenticated/admin/academic-years': typeof AuthenticatedAdminAcademicYearsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRouteWithChildren
  '/_authenticated/admin/scanner': typeof AuthenticatedAdminScannerRoute
  '/_authenticated/admin/secretaries': typeof AuthenticatedAdminSecretariesRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/secretary/groups': typeof AuthenticatedSecretaryGroupsRoute
  '/_authenticated/secretary/payments': typeof AuthenticatedSecretaryPaymentsRoute
  '/_authenticated/secretary/reception': typeof AuthenticatedSecretaryReceptionRoute
  '/_authenticated/secretary/scanner': typeof AuthenticatedSecretaryScannerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/secretary/': typeof AuthenticatedSecretaryIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/admin/payments/settings': typeof AuthenticatedAdminPaymentsSettingsRoute
  '/_authenticated/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/_authenticated/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/_authenticated/secretary/students/$id': typeof AuthenticatedSecretaryStudentsIdRoute
  '/_authenticated/secretary/students/new': typeof AuthenticatedSecretaryStudentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/admin/login'
    | '/student/login'
    | '/admin/academic-years'
    | '/admin/attendance'
    | '/admin/courses'
    | '/admin/groups'
    | '/admin/payments'
    | '/admin/scanner'
    | '/admin/secretaries'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/teachers'
    | '/secretary/groups'
    | '/secretary/payments'
    | '/secretary/reception'
    | '/secretary/scanner'
    | '/admin/'
    | '/secretary/'
    | '/student/'
    | '/teacher/'
    | '/admin/payments/settings'
    | '/admin/students/$id'
    | '/admin/students/new'
    | '/secretary/students/$id'
    | '/secretary/students/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/admin/login'
    | '/student/login'
    | '/admin/academic-years'
    | '/admin/attendance'
    | '/admin/courses'
    | '/admin/groups'
    | '/admin/payments'
    | '/admin/scanner'
    | '/admin/secretaries'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/teachers'
    | '/secretary/groups'
    | '/secretary/payments'
    | '/secretary/reception'
    | '/secretary/scanner'
    | '/admin'
    | '/secretary'
    | '/student'
    | '/teacher'
    | '/admin/payments/settings'
    | '/admin/students/$id'
    | '/admin/students/new'
    | '/secretary/students/$id'
    | '/secretary/students/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/admin/login'
    | '/student/login'
    | '/_authenticated/admin/academic-years'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/scanner'
    | '/_authenticated/admin/secretaries'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/secretary/groups'
    | '/_authenticated/secretary/payments'
    | '/_authenticated/secretary/reception'
    | '/_authenticated/secretary/scanner'
    | '/_authenticated/admin/'
    | '/_authenticated/secretary/'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
    | '/_authenticated/admin/payments/settings'
    | '/_authenticated/admin/students/$id'
    | '/_authenticated/admin/students/new'
    | '/_authenticated/secretary/students/$id'
    | '/_authenticated/secretary/students/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/': {
      id: '/_authenticated/secretary/'
      path: '/secretary'
      fullPath: '/secretary/'
      preLoaderRoute: typeof AuthenticatedSecretaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/scanner': {
      id: '/_authenticated/secretary/scanner'
      path: '/secretary/scanner'
      fullPath: '/secretary/scanner'
      preLoaderRoute: typeof AuthenticatedSecretaryScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/reception': {
      id: '/_authenticated/secretary/reception'
      path: '/secretary/reception'
      fullPath: '/secretary/reception'
      preLoaderRoute: typeof AuthenticatedSecretaryReceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/payments': {
      id: '/_authenticated/secretary/payments'
      path: '/secretary/payments'
      fullPath: '/secretary/payments'
      preLoaderRoute: typeof AuthenticatedSecretaryPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/groups': {
      id: '/_authenticated/secretary/groups'
      path: '/secretary/groups'
      fullPath: '/secretary/groups'
      preLoaderRoute: typeof AuthenticatedSecretaryGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/secretaries': {
      id: '/_authenticated/admin/secretaries'
      path: '/admin/secretaries'
      fullPath: '/admin/secretaries'
      preLoaderRoute: typeof AuthenticatedAdminSecretariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/scanner': {
      id: '/_authenticated/admin/scanner'
      path: '/admin/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AuthenticatedAdminScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/academic-years': {
      id: '/_authenticated/admin/academic-years'
      path: '/admin/academic-years'
      fullPath: '/admin/academic-years'
      preLoaderRoute: typeof AuthenticatedAdminAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/students/new': {
      id: '/_authenticated/secretary/students/new'
      path: '/secretary/students/new'
      fullPath: '/secretary/students/new'
      preLoaderRoute: typeof AuthenticatedSecretaryStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/students/$id': {
      id: '/_authenticated/secretary/students/$id'
      path: '/secretary/students/$id'
      fullPath: '/secretary/students/$id'
      preLoaderRoute: typeof AuthenticatedSecretaryStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students/new': {
      id: '/_authenticated/admin/students/new'
      path: '/new'
      fullPath: '/admin/students/new'
      preLoaderRoute: typeof AuthenticatedAdminStudentsNewRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
    '/_authenticated/admin/students/$id': {
      id: '/_authenticated/admin/students/$id'
      path: '/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIdRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
    '/_authenticated/admin/payments/settings': {
      id: '/_authenticated/admin/payments/settings'
      path: '/settings'
      fullPath: '/admin/payments/settings'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminPaymentsRoute
    }
  }
}

interface AuthenticatedAdminPaymentsRouteChildren {
  AuthenticatedAdminPaymentsSettingsRoute: typeof AuthenticatedAdminPaymentsSettingsRoute
}

const AuthenticatedAdminPaymentsRouteChildren: AuthenticatedAdminPaymentsRouteChildren =
  {
    AuthenticatedAdminPaymentsSettingsRoute:
      AuthenticatedAdminPaymentsSettingsRoute,
  }

const AuthenticatedAdminPaymentsRouteWithChildren =
  AuthenticatedAdminPaymentsRoute._addFileChildren(
    AuthenticatedAdminPaymentsRouteChildren,
  )

interface AuthenticatedAdminStudentsRouteChildren {
  AuthenticatedAdminStudentsIdRoute: typeof AuthenticatedAdminStudentsIdRoute
  AuthenticatedAdminStudentsNewRoute: typeof AuthenticatedAdminStudentsNewRoute
}

const AuthenticatedAdminStudentsRouteChildren: AuthenticatedAdminStudentsRouteChildren =
  {
    AuthenticatedAdminStudentsIdRoute: AuthenticatedAdminStudentsIdRoute,
    AuthenticatedAdminStudentsNewRoute: AuthenticatedAdminStudentsNewRoute,
  }

const AuthenticatedAdminStudentsRouteWithChildren =
  AuthenticatedAdminStudentsRoute._addFileChildren(
    AuthenticatedAdminStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAcademicYearsRoute: typeof AuthenticatedAdminAcademicYearsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRouteWithChildren
  AuthenticatedAdminScannerRoute: typeof AuthenticatedAdminScannerRoute
  AuthenticatedAdminSecretariesRoute: typeof AuthenticatedAdminSecretariesRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRouteWithChildren
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedSecretaryGroupsRoute: typeof AuthenticatedSecretaryGroupsRoute
  AuthenticatedSecretaryPaymentsRoute: typeof AuthenticatedSecretaryPaymentsRoute
  AuthenticatedSecretaryReceptionRoute: typeof AuthenticatedSecretaryReceptionRoute
  AuthenticatedSecretaryScannerRoute: typeof AuthenticatedSecretaryScannerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedSecretaryIndexRoute: typeof AuthenticatedSecretaryIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedSecretaryStudentsIdRoute: typeof AuthenticatedSecretaryStudentsIdRoute
  AuthenticatedSecretaryStudentsNewRoute: typeof AuthenticatedSecretaryStudentsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAcademicYearsRoute: AuthenticatedAdminAcademicYearsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRouteWithChildren,
  AuthenticatedAdminScannerRoute: AuthenticatedAdminScannerRoute,
  AuthenticatedAdminSecretariesRoute: AuthenticatedAdminSecretariesRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRouteWithChildren,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedSecretaryGroupsRoute: AuthenticatedSecretaryGroupsRoute,
  AuthenticatedSecretaryPaymentsRoute: AuthenticatedSecretaryPaymentsRoute,
  AuthenticatedSecretaryReceptionRoute: AuthenticatedSecretaryReceptionRoute,
  AuthenticatedSecretaryScannerRoute: AuthenticatedSecretaryScannerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedSecretaryIndexRoute: AuthenticatedSecretaryIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedSecretaryStudentsIdRoute: AuthenticatedSecretaryStudentsIdRoute,
  AuthenticatedSecretaryStudentsNewRoute:
    AuthenticatedSecretaryStudentsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
